# Generated by Django 5.0.2 on 2024-04-29 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test_app',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_app',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='test_app.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='test_app',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woman', to='test_app.husband', verbose_name='Муж'),
        ),
        migrations.AddField(
            model_name='test_app',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='test_app.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='test_app',
            index=models.Index(fields=['-time_create'], name='test_app_te_time_cr_aff3b5_idx'),
        ),
    ]
