# Generated by Django 5.0.2 on 2024-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_app',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='test_app',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='test_app',
            index=models.Index(fields=['-time_create'], name='test_app_te_time_cr_aff3b5_idx'),
        ),
    ]
