# Generated by Django 5.0.2 on 2024-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_test_app_options_test_app_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_app',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
