# Generated by Django 5.0.2 on 2024-03-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_test_app_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_app',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
