# Generated by Django 5.0.2 on 2024-03-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_category_test_app_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_app',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.category'),
        ),
    ]
